version: '3'
services:
  book_service:
    build: ./book_service
    ports:
      - "8000:8000"

  user_service:
    build: ./user_service
    ports:
      - "8001:8001"

  order_service:
    build: ./order_service
    ports:
      - "8002:8002"